PAWReg/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('client.urls')),
    path('console/', include('console.urls')),
    path('merchant/', include('merchant.urls')),
    path('admin/', admin.site.urls),
]

console/urls.py
from django.urls import path

from .views import ConsoleIndexPageView, EventsListPageView, EventsCreatePageView, EventsDetailsPageView, MembershipsCreatePageView, MembershipsDetailPageView, ProductCreatePageView, ProductDetailPageView

app_name = 'console'
urlpatterns = [
    path('', ConsoleIndexPageView.as_view(), name='index'),
    path('events', EventsListPageView.as_view(), name='events-list'),
    path('events/new', EventsCreatePageView.as_view(), name='events-create'),
    path('events/<int:event_id>', EventsDetailsPageView.as_view(), name='events-detail'),
    path('events/<int:event_id>/memberships', MembershipsCreatePageView.as_view(), name='memberships-create'),
    path('events/<int:event_id>/memberships/<int:membership_id>', MembershipsDetailPageView.as_view(), name='memberships-detail'),
    path('events/<int:event_id>/products', ProductCreatePageView.as_view(), name='products-create'),
    path('events/<int:event_id>/products/<int:product_id>', ProductDetailPageView.as_view(), name='products-detail'),
]

console/models.py
from django.db import models

# Create your models here.

console/forms/event_form.py
from django import forms

from shared.models import Event, ProductType, Product, Membership


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = '__all__'

console/forms/membership_form.py
from django import forms

from shared.models import Event, ProductType, Product, Membership

class MembershipForm(forms.ModelForm):
    class Meta:
        model = Membership
        fields = (
            'name_short',
            'name_long',
            'product_description',
            'tier1_pricing',
            'tier2_pricing',
            'tier3_pricing',
            'available_at_event',
            'available_pre_event',
            'available_parents',
            'available_merchants',
            'included_products',
        )

console/forms/product_form.py
from django import forms

from shared.models import Event, ProductType, Product, Membership

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = (
            'product_type',
            'name_short',
            'name_long',
            'product_description',
            'cart_max',
            'tier1_pricing',
            'tier2_pricing',
            'tier3_pricing',
            'customer_modifiable',
            'available_at_event',
            'available_pre_event',
        )

console/views/console_index.py
from django.views.generic.base import TemplateView

class ConsoleIndexPageView(TemplateView):
    template_name = 'console_index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

console/views/events_create.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView

from ..forms import EventForm

class EventsCreatePageView(TemplateView):
    template_name = 'events_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = EventForm()
        return context

    def post(self, request, **kwargs):
        context = self.get_context_data(**kwargs)

        form = EventForm(request.POST)
        context['form'] = form

        if form.is_valid:
            result = form.save()
            return HttpResponseRedirect(reverse('console:events-list'))
        
        return self.render_to_response(context)

console/views/events_detail.py
from django.views.generic.base import TemplateView

from shared.models import Event, Product, Membership

from ..forms import EventForm

class EventsDetailsPageView(TemplateView):
    template_name = 'events_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        event = Event.objects.get(pk=kwargs['event_id'])
        memberships = Membership.objects.filter(event=event)
        products = Product.objects.all().filter(event=event)

        context['memberships'] = memberships
        context['products'] = products
        context['event'] = event

        context['form'] = EventForm(instance=event)
        
        return context
    
    def post(self, request, **kwargs):
        context = self.get_context_data(**kwargs)

        form = EventForm(request.POST, instance=context['event'])
        context['form'] = form
        
        if form.is_valid():
            form.save()

        return self.render_to_response(context)

console/views/events_list.py
from django.views.generic.base import TemplateView

from shared.models import Event

class EventsListPageView(TemplateView):
    template_name = 'events_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['events'] = Event.objects.all()
        return context

console/views/memberships_create.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView

from ..forms import MembershipForm
from shared.models import Event, Membership

class MembershipsCreatePageView(TemplateView):
    template_name = 'memberships_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        event = Event.objects.get(pk=kwargs['event_id'])
        context['event'] = event
        context['form'] = MembershipForm()

        return context
    
    def post(self, request, **kwargs):
        context = self.get_context_data(**kwargs)
        form = MembershipForm(request.POST)
        context['form'] = form

        if form.is_valid():
            membership = form.save(commit=False)
            membership.event = context['event']
            membership.save()
            form.save_m2m()
            return HttpResponseRedirect(reverse('console:events-detail', args=[context['event'].id]))
        
        return self.render_to_response(context)

console/views/memberships_detail.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView

from ..forms import MembershipForm
from shared.models import Event, Membership


class MembershipsDetailPageView(TemplateView):
    template_name = 'memberships_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        event = Event.objects.get(pk=kwargs['event_id'])
        membership = Membership.objects.get(pk=kwargs['membership_id'])

        context['event'] = event
        context['membership'] = membership

        context['form'] = MembershipForm(instance=membership)

        return context
    
    def post(self, request, **kwargs):
        context = self.get_context_data(**kwargs)

        form = MembershipForm(request.POST, instance=context['membership'])
        context['form'] = form

        if form.is_valid():
            form.save()

        return self.render_to_response(context)

console/views/product_create.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView

from ..forms import ProductForm
from shared.models import Event, Membership, Product

class ProductCreatePageView(TemplateView):
    template_name = 'products_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        event = Event.objects.get(pk=kwargs['event_id'])
        context['event'] = event
        context['form'] = ProductForm()

        return context
    
    def post(self, request, **kwargs):
        context = self.get_context_data(**kwargs)
        event = Event.objects.get(pk=kwargs['event_id'])
        
        form = ProductForm(request.POST)
        context['form'] = form

        if form.is_valid():
            product = form.save(commit=False)
            product.event = event
            product.save()
            return HttpResponseRedirect(reverse('console:events-detail', args=[event.id]))
        
        return self.render_to_response(context)

console/views/product_details.py
from django.urls import reverse
from django.views.generic.base import TemplateView

from ..forms import ProductForm
from shared.models import Event, Product

class ProductDetailPageView(TemplateView):
    template_name = 'products_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        event = Event.objects.get(pk=kwargs['event_id'])
        product = Product.objects.get(pk=kwargs['product_id'])

        context['event'] = event
        context['product'] = product
        context['form'] = ProductForm(instance=product)

        return context
    
    def post(self, request, **kwargs):
        context = self.get_context_data(**kwargs)

        form = ProductForm(request.POST, instance=context['product'])
        context['form'] = form
        
        if form.is_valid():
            form.save()

        return self.render_to_response(context)

console/templates/console_index.html
{% extends 'base.html' %}

{% block title %}PAWReg - Console{% endblock %}

{% block content %}
<div class="pt-5 row">
    <div class="col-2">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Admin</h5>
                <ul class="nav nav-pills flex-column">
                    <li class="nav-item">
                        <a href="{% url 'console:events-list' %}" class="nav-link">Events</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="card mt-1">
            <div class="card-body">
                <h5 class="card-title">Registration</h5>
                <ul class="nav nav-pills flex-column">
                    <li class="nav-item">
                        <a href="" class="nav-link">Registrations</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col">
        {% block console_section %}
        {% endblock %}
    </div>
</div>
{% endblock %}

console/templates/events_create.html
{% extends 'console_index.html' %}

{% block title %}PAWReg - Console - New Event{% endblock %}

{% block console_section %}
<div class="row">
    <div class="col">
        <h1>New Event</h1>
    </div>
</div>
<div class="row">
    <div class="col">
        <form action="{% url 'console:events-create' %}" method="POST" class="form">
            {% csrf_token %}
            {{form.as_div}}
            <button type="submit" class="btn btn-primary">Create Event</button>
        </form>
    </div>
</div>
{% endblock %}

console/templates/events_detail.html
{% extends 'console_index.html' %}

{% block title %}PAWReg - Console - View Event{% endblock %}

{% block console_section %}
<div class="row">
    <div class="col">
        <h1>Event Details</h1>
    </div>
</div>
<div class="row">
    <div class="col">
        <form action="{% url 'console:events-detail' event.id %}" method="POST" class="form-sm">
            {% csrf_token %}
            {{form.as_div}}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>
<div class="row mb-3">
    <div class="col">
        <h2>Products</h2>
        
        <a href="{% url 'console:products-create' event.id %}" class="btn btn-primary">Create Product</a>
        <a href="{% url 'console:memberships-create' event.id %}" class="btn btn-primary">Create Membership</a>
    </div>
</div>
<div class="row">
    <div class="col">
        <table class="table table-striped">
            <thead class="table-dark">
                <td>Short Name</td>
                <td>Long Name</td>
                <td>Tier 1 Pricing</td>
                <td>Tier 2 Pricing</td>
                <td>Tier 3 Pricing</td>
            </thead>
            <tbody>
                <tr>
                    <td colspan="5" class="table-info">Products</td>
                </tr>
                {% for product in products %}
                <tr>
                    <td>
                        <a href="{% url 'console:products-detail' event.id product.id %}">{{product.name_short}}</a>
                    </td>
                    <td>{{product.name_long}}</td>
                    <td>{{product.tier1_pricing}}</td>
                    <td>{{product.tier2_pricing}}</td>
                    <td>{{product.tier3_pricing}}</td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="5" class="table-info">Memberships</td>
                </tr>
                {% for membership in memberships %}
                <tr>
                    <td>
                        <a
                            href="{% url 'console:memberships-detail' event.id membership.id %}">{{membership.name_short}}</a>
                    </td>
                    <td>{{membership.name_long}}</td>
                    <td>{{membership.tier1_pricing}}</td>
                    <td>{{membership.tier2_pricing}}</td>
                    <td>{{membership.tier3_pricing}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

console/templates/events_list.html
{% extends 'console_index.html' %}

{% block title %}PAWReg - Console - Events{% endblock %}

{% block console_section %}
<div class="row">
    <div class="col">
        <h1>Events</h1>
        <a href="{% url 'console:events-create' %}" class="btn btn-primary">Create Event</a>
    </div>
</div>
<div class="row pt-2">
    <div class="col">
        <table class="table table-striped">
            <thead class="table-dark">
                <td>Short Name</td>
                <td>Long Name</td>
                <td>Start Date</td>
                <td>End Date</td>
            </thead>
            <tbody>
                {% for event in events %}
                <tr>
                    <td>
                        <a href="{% url 'console:events-detail' event.id %}">{{ event.name_short }}</a>
                    </td>
                    <td>{{ event.name_long }}</td>
                    <td>{{ event.event_start_date }}</td>
                    <td>{{ event.event_end_date }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

console/templates/memberships_create.html
{% extends 'console_index.html' %}

{% block title %}PAWReg - Console - New Membership{% endblock %}

{% block console_section %}
<div class="row">
    <div class="col">
        <h1>New Membership</h1>
    </div>
</div>
<div class="row">
    <div class="col mb-3">
        <form action="{% url 'console:memberships-create' event.id %}" method="post" class="form">
            {% csrf_token %}
            {{form.as_div}}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>
{% endblock %}

console/templates/memberships_detail.html
{% extends 'console_index.html' %}

{% block title %}PAWReg - Console - Modify Membership{% endblock %}

{% block console_section %}
<div class="row">
    <div class="col">
        <h1>New Membership</h1>
    </div>
</div>
<div class="row">
    <div class="col mb-3">
        <form action="{% url 'console:memberships-detail' event.id membership.id %}" method="post" class="form">
            {% csrf_token %}
            {{form.as_div}}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>
{% endblock %}

console/templates/products_create.html
{% extends 'console_index.html' %}

{% block title %}PAWReg - Console - New Product{% endblock %}

{% block console_section %}
<div class="row">
    <div class="col">
        <h1>New Product</h1>
    </div>
</div>
<div class="row">
    <div class="col mb-3">
        <form action="{% url 'console:products-create' event.id %}" method="post" class="form">
            {% csrf_token %}
            {{form.as_div}}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>
{% endblock %}

console/templates/products_detail.html
{% extends 'console_index.html' %}

{% block title %}PAWReg - Console - Modify Product{% endblock %}

{% block console_section %}
<div class="row">
    <div class="col">
        <h1>New Product</h1>
    </div>
</div>
<div class="row">
    <div class="col mb-3">
        <form action="{% url 'console:products-detail' event.id product.id %}" method="post" class="form">
            {% csrf_token %}
            {{form.as_div}}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>
{% endblock %}