PAWReg/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('client.urls')),
    path('console/', include('console.urls')),
    path('merchant/', include('merchant.urls')),
    path('admin/', admin.site.urls),
]

client/urls.py
from django.urls import path

from .views import HomePageView, DayPassPageView, ForgotPasswordPageView
from .views import SignupPageView, SigninPageView, SignoutPageView, ProfilePageView
from .views import RegisterPageView, SelectMembershipPageView, SelectProductsPageView
from .views import RegisterPaymentPageView, RegisterParentPageView, RegisterMerchantPageView
from .views import RegisterPartyPageView, RegisterVolunteerPageView

app_name = 'client'
urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path ('day_pass', DayPassPageView.as_view(), name='day-pass'),
    path('forgot', ForgotPasswordPageView.as_view(), name='forgot'),
    path('signup', SignupPageView.as_view(), name='signup'),
    path('signin', SigninPageView.as_view(), name='signin'),
    path('signout', SignoutPageView.as_view(), name='signout'),
    path('profile', ProfilePageView.as_view(), name='profile'),
    path('register', RegisterPageView.as_view(), name='register'),
    path('register/membership', SelectMembershipPageView.as_view(), name='register-membership'),
    path('register/products', SelectProductsPageView.as_view(), name='register-products'),
    path('register/parent', RegisterParentPageView.as_view(), name='register-parent'),
    path('register/merchant', RegisterMerchantPageView.as_view(), name='register-merchant'),
    path('register/party', RegisterPartyPageView.as_view(), name='register-party'),
    path('register/volunteer', RegisterVolunteerPageView.as_view(), name='register-volunteer'),
    path('register/payment', RegisterPaymentPageView.as_view(), name='register-payment'),
]

client/forms/account_form.py
from django.contrib.auth.forms import UserChangeForm

from shared.models import User

class AccountForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name')

client/views/day_pass.py
from django.views.generic.base import TemplateView

class DayPassPageView(TemplateView):
    template_name = 'home_day_pass.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

client/views/forgot_password.py
from django.views.generic.base import TemplateView

class ForgotPasswordPageView(TemplateView):
    template_name = 'home_forgot_password.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

client/views/home_page.py
from django.views.generic.base import TemplateView

from ..forms.signin_form import SigninForm

class HomePageView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['is_authenticated'] = True;
        else: 
            context['signin_form'] = SigninForm()
        return context

client/views/profile.py
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView
from django.utils.decorators import method_decorator

from ..forms import AccountForm, ProfileForm
from shared.models import Profile


@method_decorator(login_required, name='dispatch')
class ProfilePageView(TemplateView):
    template_name = 'home_profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        profile = None
        if Profile.objects.filter(user=self.request.user).count() > 0:
            profile = Profile.objects.get(user=self.request.user)

        account_form = AccountForm(instance=self.request.user)
        profile_form = ProfileForm(instance=profile)

        context['account_form'] = account_form
        context['profile_form'] = profile_form

        return context
    
    def post(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        form_name = request.POST['form']

        if form_name == 'Account':
            account_form = AccountForm(request.POST, instance=self.request.user)

            context['account_form'] = account_form

            if account_form.is_valid():
                account_form.save()

        if form_name == 'Profile':
            profile = None
            if Profile.objects.filter(user=self.request.user).count() > 0:
                profile = Profile.objects.get(user=self.request.user)

            profile_form = ProfileForm(self.request.POST, instance=profile)

            context['profile_form'] = profile_form

            if profile_form.is_valid():
                profile = profile_form.save(commit=False)
                profile.user = self.request.user
                profile.save()
        
        return self.render_to_response(context)
        

client/views/register.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView

from ..forms import RegistrationForm
from shared.models import get_current_event
from shared.models import Event, Membership, User, Registration


@method_decorator(login_required, name='dispatch')
class RegisterPageView(TemplateView):
    template_name = 'home_register.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        event = get_current_event()
        registration = None
        try:
            registration = Registration.objects.get(user=self.request.user, event=event)
        except Registration.DoesNotExist:
            registration = None
    
        context['registration'] = registration
        
        context['form'] = RegistrationForm(instance=registration)

        return context
    
    def post(self, request, **kwargs):
        context = self.get_context_data(**kwargs)

        form = RegistrationForm(request.POST, instance=context['registration'])
        context['form'] = form

        if form.is_valid():
            registration = form.save(commit=False)
            registration.event = get_current_event()
            registration.user = request.user
            registration.save()
            return HttpResponseRedirect(reverse('client:register-membership'))
        
        return self.render_to_response(context)

client/views/register_membership.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView

from shared.models import get_current_event
from shared.models import Event, User, Membership, Registration


@method_decorator(login_required, name='dispatch')
class SelectMembershipPageView(TemplateView):
    template_name = 'register_membership.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        event = get_current_event()
        registration = Registration.objects.get(user=self.request.user, event=event)
        memberships = Membership.objects.filter(event=event)
        context['registration'] = registration
        context['memberships'] = memberships

        return context
    
    def post(self, request, **kwargs):
        context = self.get_context_data(**kwargs)

        membership = Membership.objects.get(pk=request.POST['membership'])
        context['registration'].membership = membership
        context['registration'].save()

        return HttpResponseRedirect(reverse('client:register-products'))

client/views/register_merchant.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView

from shared.models import get_current_event
from shared.models import Event, User, Registration, Membership
from merchant.models import Merchant

from merchant.forms import MerchantForm

@method_decorator(login_required, name='dispatch')
class RegisterMerchantPageView(TemplateView):
    template_name = 'register_merchant.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        event = get_current_event()
        registration = Registration.objects.get(user=self.request.user, event=event)
        membership = registration.membership
        
        merchant = None
        try:
            merchant = Merchant.objects.get(event=event, user=self.request.user)
        except Merchant.DoesNotExist:
            merchant = None
        
        context['event'] = event
        context['registration'] = registration
        context['membership'] = membership
        context['merchant'] = merchant
        context['form'] = MerchantForm(instance=merchant)

        return context

    def post(self, request, **kwargs):
        context = self.get_context_data(**kwargs)

        form = MerchantForm(request.POST, instance=context['merchant'])
        context['form'] = form

        if form.is_valid:
            merchant = form.save(commit=False)
            merchant.event = context['event']
            merchant.user = request.user
            merchant.save()
        else:
            return self.render_to_response(context)
        
        if context['registration'].is_party_host:
            return HttpResponseRedirect(reverse('client:register-party'))
        elif context['registration'].is_volunteer:
            return HttpResponseRedirect(reverse('client:register-volunteer'))
        else:
            return HttpResponseRedirect(reverse('client:register-payment'))
        endif

client/views/register_parent.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView

from shared.models import get_current_event
from shared.models import Event, User, Membership, Registration, RegistrationProduct, Product, ProductTypeAttribute


@method_decorator(login_required, name='dispatch')
class RegisterParentPageView(TemplateView):
    template_name = 'register_parent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

client/views/register_party.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView

from shared.models import get_current_event
from shared.models import Event, User, Membership, Registration, RegistrationProduct, Product, ProductTypeAttribute


@method_decorator(login_required, name='dispatch')
class RegisterPartyPageView(TemplateView):
    template_name = 'register_party.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

client/views/register_payment.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView

from shared.models import get_current_event
from shared.models import Event, User, Membership, Registration, RegistrationProduct, Product, ProductTypeAttribute


@method_decorator(login_required, name='dispatch')
class RegisterPaymentPageView(TemplateView):
    template_name = 'register_payment.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        event = get_current_event()
        registration = Registration.objects.get(user=self.request.user, event=event)
        context['registration'] = registration

        return context

    def post(self, request, **kwargs):
        context = self.get_context_data(**kwargs)

        if request.POST.get('is_paid', False):
            context['registration'].is_paid = True
            context['registration'].save()
            return HttpResponseRedirect(reverse('client:index'))
        else:
            return self.render_to_response(context)
        endif

client/views/register_products.py
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView

from shared.models import get_current_event
from shared.models import Event, User, Membership, Registration, RegistrationProduct, Product, ProductTypeAttribute


@method_decorator(login_required, name='dispatch')
class SelectProductsPageView(TemplateView):
    template_name = 'register_products.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        event = get_current_event()
        registration = Registration.objects.get(user=self.request.user, event=event)
        membership = registration.membership
        included_products = membership.included_products.all()
        additional_products = Product.objects.exclude(id__in=[ip.id for ip in included_products])
        product_type_attributes = ProductTypeAttribute.objects.all()
        context['registration'] = registration
        context['membership'] = membership
        context['included_products'] = included_products
        context['additional_products'] = additional_products
        context['product_type_attributes'] = product_type_attributes

        return context
    
    def post(self, request, **kwargs):
        context = self.get_context_data(**kwargs)

        for included_product in context['included_products']:
            registration_product = RegistrationProduct()
            registration_product.membership = context['membership']
            registration_product.product = included_product

            attr_key = 'included_product_' + str(included_product.id) + '_attr'
            if request.POST.get(attr_key, None) != None:
                registration_product.attribute = request.POST[attr_key]

            registration_product.value = 0.00
            registration_product.save()


        for product in context['additional_products']:
            product_key = 'product_' + str(product.id)
            product_attr_key = 'product_' + str(product.id) + '_attr'
            product_value_key = 'product_' + str(product.id) + '_value'

            if request.POST.get(product_key, None) != None:
                registration_product = RegistrationProduct()
                registration_product.membership = context['membership']
                registration_product.product = product

                if request.POST.get(product_attr_key, None) != None:
                    registration_product.attribute = request.POST[product_attr_key]
                    registration_product.value = product.tier1_pricing
                
                if request.POST.get(product_value_key, None) != None:
                    registration_product.value = request.POST[product_value_key]
                
                registration_product.save()

        if context['registration'].is_parent:
            return HttpResponseRedirect(reverse('client:register-parent'))
        elif context['registration'].is_merchant:
            return HttpResponseRedirect(reverse('client:register-merchant'))
        elif context['registration'].is_party_host:
            return HttpResponseRedirect(reverse('client:register-party'))
        elif context['registration'].is_volunteer:
            return HttpResponseRedirect(reverse('client:register-volunteer'))
        else:
            return HttpResponseRedirect(reverse('client:register-payment'))
        endif

client/views/register_volunteer.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic.base import TemplateView

from shared.models import Event, User, Membership, Registration, RegistrationProduct, Product, ProductTypeAttribute
from shared.models import get_current_event


@method_decorator(login_required, name='dispatch')
class RegisterVolunteerPageView(TemplateView):
    template_name = 'register_volunteer.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

client/views/signin.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic.base import TemplateView

from ..forms import SigninForm

class SigninPageView(TemplateView):
    template_name = 'home_signin.html'
    http_method_names = ['get', 'post']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['signin_form'] = SigninForm()
        return context
        
    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        form = SigninForm(request.POST)
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(request.GET.get('next', '/'))
        else:
            context = self.get_context_data(**kwargs)
            return self.render_to_response(context)

client/templates/home.html
{% extends 'base.html' %}

{% block title %}PAWReg{% endblock %}

{% block content %}
{% if not is_authenticated %}
<div class="row mt-5 justify-content-center">
    <div class="col-4">
        <div class="card">
            <form action="{% url 'client:signin' %}" method="post" class="form">
                <div class="card-body">
                    <p class="h5">Account Login</p>
                        {% csrf_token %}
                        {{signin_form.as_div}}
                </div>
                <div class="card-footer">
                    <div>
                        <button type="submit" class="btn btn-primary">Login</button>
                        <a href="{% url 'client:forgot' %}" class="btn btn-secondary">Forgot Password</a>
                    </div>
                    <a href="{% url 'client:signup' %}">Create Account</a>
                </div>
            </form>
        </div>
    </div>
    <div class="col-4 justify-content-center">
        <div class="card">
            <div class="card-body">
                <p class="h5">Day Pass</p>
                <p>Only going to be here for a single day?</p>
            </div>
            <div class="card-footer">
                <div>
                    <a href="{% url 'client:day-pass' %}" class="btn btn-primary">Get A Day Pass</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="row pt-2">
    <div class="col">
        <h1>Welcome {{ request.user.first_name }}</h1>

        <div class="row">
            <div class="col-sm-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Profile</h5>
                        <p class="card-text">Need to change your profile info?</p>
                        <a href="{% url 'client:profile' %}" class="btn btn-primary">Profile</a>
                    </div>
                </div>
            </div>

            <div class="col-sm-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Register</h5>
                        <p class="card-text">Ready to registerfor {{ event.name_long }}?</p>
                        <a href="{% url 'client:register' %}" class="btn btn-primary">Register Now</a>
                    </div>
                </div>
            </div>
        </div>

        <h3>Event History</h3>
        <table class="table table-striped">
            <thead class="table-dark">
                <td>Event Name</td>
                <td>Dates</td>
            </thead>
            <tbody>
                {% for event in events %}
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endif %}
{% endblock %}

client/templates/home_day_pass.html
{% extends 'base.html' %}

{% block title %}PAWReg - Day Pass{% endblock %}

{% block content %}
{% endblock %}

client/templates/home_forgot_password.html
{% extends 'base.html' %}

{% block title %}PAWReg - Forgot Password{% endblock %}

{% block content %}
{% endblock %}

client/templates/home_profile.html
{% extends 'base.html' %}

{% block title %}PAWReg - Profile{% endblock %}

{% block content %}
<div class="row mt-5">
    <div class="col-2">
        <h1>My Profile</h1>
    </div>
</div>
<div class="row">
    <div class="col-4">
        <div class="card">
            <form action="{% url 'client:profile' %}" method="post" class="form">
                {% csrf_token %}
                <div class="card-body">
                    <p class="h5 card-title">Account Info</p>
                    <input type="hidden" name="form" value="Account">
                    {{account_form.as_div}}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
    <div class="col-4">
        <div class="card">
            <form action="{% url 'client:profile' %}" method="post" class="form">
                {% csrf_token %}
                <div class="card-body">
                    <p class="h5 card-title">Profile Info</p>
                    <input type="hidden" name="form" value="Profile">
                    {{profile_form.as_div}}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

client/templates/home_register.html
{% extends 'base.html' %}

{% block title %}PAWReg - Register{% endblock %}

{% block content %}
<div class="row mt-5">
    <div class="col-4 justify-content-center">
        <div class="card">
            <form action="{% url 'client:register' %}" method="post" class="form">
                {% csrf_token %}
                <div class="card-body">
                    <p class="h5 card-title">Basics</p>
                    {{form.as_div}}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

client/templates/home_signin.html
{% extends 'base.html' %}

{% block title %}PAWReg - Sign In{% endblock %}

{% block content %}
<div class="row mt-5 justify-content-center">
    <div class="col-4">
        <div class="card">
            <form action="{{ request.get_full_path }}" method="post" class="form">
                <div class="card-body">
                    <p class="h5">Account Login</p>
                    {% csrf_token %}
                    {{signin_form.as_div}}
                </div>
                <div class="card-footer">
                    <div>
                        <button type="submit" class="btn btn-primary">Login</button>
                        <a href="{% url 'client:forgot' %}" class="btn btn-secondary">Forgot Password</a>
                    </div>
                    <a href="{% url 'client:signup' %}">Create Account</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

client/templates/home_signup.html
{% extends 'base.html' %}

{% block title %}PAWReg - Create Account{% endblock %}

{% block content %}
<div class="row mt-5 justify-content-center">
    <div class="col-4">
        <div class="card">
            <form action="{% url 'client:signup' %}" method="post" class="form">
                {% csrf_token %}
                <div class="card-body">
                    <p class="h5">Account Login</p>
                    {{ signup_form.as_div }}
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Create Account</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

client/templates/register_membership.html
{% extends 'base.html' %}

{% block title %}PAWReg - Select Membership{% endblock %}

{% block content %}
<div class="row mt-5">
    <h1>Select Membership</h1>
</div>
{% for membership in memberships %}
<div class="row mt-2">
    <div class="col-4 justify-content-center">
        <div class="card">
            <form action="{% url 'client:register-membership' %}" method="post" class="form">
                {% csrf_token %}
                <input type="hidden" name="membership" value="{{membership.id}}">
                <div class="card-body">
                    <p class="h5 card-title">{{membership.name_long}}</p>
                    <p>{{membership.product_description}}</p>
                    <p><strong>Price:</strong> ${{membership.tier1_pricing}}</p>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Select</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

client/templates/register_merchant.html
{% extends 'base.html' %}

{% block title %}PAWReg - Merchant Application{% endblock %}

{% block content %}
<div class="row mt-5">
    <div class="col">
        <h1>Merchant Application</h1>
    </div>
</div>
<div class="row">
    <div class="col">
        <form action="{% url 'client:register-merchant' %}" method="post" class="form">
            {% csrf_token %}
            {{form.as_div}}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>
{% endblock %}

client/templates/register_parent.html
{% extends 'base.html' %}

{% block title %}PAWReg - Child Badges{% endblock %}

{% block content %}
<div class="row mt-5">
    <div class="col">
        <h1>Child Badges</h1>
    </div>
</div>
{% endblock %}

client/templates/register_party.html
{% extends 'base.html' %}

{% block title %}PAWReg - Party Host Application{% endblock %}

{% block content %}
<div class="row mt-5">
    <div class="col">
        <h1>Party Host Application</h1>
    </div>
</div>
{% endblock %}

client/templates/register_payment.html
{% extends 'base.html' %}

{% block title %}PAWReg - Payment{% endblock %}

{% block content %}
<div class="row mt-5">
    <h1>Payment</h1>
</div>
<form action="{% url 'client:register-payment' %}" method="post" class="form">
    {% csrf_token %}
    <div class="row">
        <div class="col">
            <input type="checkbox" class="form-check-input" name="is_paid" id="is_paid">
            <label class="form-check-label" for="is_paid">Is Paid</label>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <button type="submit" class="btn btn-primary">Save Selection</button>
        </div>
    </div>
</form>
{% endblock %}

client/templates/register_products.html
{% extends 'base.html' %}

{% block title %}PAWReg - Select Products{% endblock %}

{% block content %}
<div class="row mt-5">
    <h1>Select Products</h1>
</div>
<form action="{% url 'client:register-products' %}" method="post" class="form">
    {% csrf_token %}
    <div class="row">
        <h2>Included Products - {{membership.name_long}}</h2>
    </div>
    <div class="row">
        {% for included_product in included_products %}
        <div class="col-3">
            <div class="card h-100">
                <div class="card-header">
                    <h5 class="card-title">{{included_product.name_long}}</h5>
                </div>
                <div class="card-body">
                    <p>{{included_product.product_description}}</p>
                </div>
                {% if included_product.product_type.user_selection_required %}
                <div class="card-footer">
                    <select class="form-select" name="included_product_{{included_product.id}}_attr">
                        {% for attribute in product_type_attributes %}
                        <option value="{{attribute.name_short}}">{{attribute.name_long}}</option>
                        {% endfor %}
                    </select>
                </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="row mt-2">
        <h2>Additional Products</h2>
    </div>
    <div class="row">
        {% for additional_product in additional_products %}
        <div class="col-3">
            <div class="card h-100">
                <div class="card-header">
                    <input type="checkbox" class="form-check-input" id="product_{{additional_product.id}}" name="product_{{additional_product.id}}">
                    <label class="form-check-label" for="product_{{additional_product.id}}">
                        <h5 class="card-title">{{additional_product.name_long}}</h5>
                    </label>
                </div>
                <div class="card-body">
                    <p>{{additional_product.product_description}}</p>
                </div>
                {% if additional_product.product_type.user_selection_required %}
                <div class="card-footer">
                    <select class="form-select">
                        {% for attribute in product_type_attributes %}
                        <option>{{attribute.name_long}}</option>
                        {% endfor %}
                    </select>
                </div>
                {% endif %}
                {% if additional_product.customer_modifiable %}
                <div class="card-footer">
                    <div class="input-group mb-3">
                        <span class="input-group-text">$</span>
                        <input type="text" class="form-control" name="product_{{additional_product.id}}_value" value="{{additional_product.tier1_pricing}}">
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="row mt-2">
        <div class="col">
            <button type="submit" class="btn btn-primary">Save Selection</button>
        </div>
    </div>
</form>
{% endblock %}

client/templates/register_volunteer.html
{% extends 'base.html' %}

{% block title %}PAWReg - Volunteer Application{% endblock %}

{% block content %}
<div class="row mt-5">
    <div class="col">
        <h1>Volunteer Application</h1>
    </div>
</div>
{% endblock %}