PAWReg/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('client.urls')),
    path('console/', include('console.urls')),
    path('merchant/', include('merchant.urls')),
    path('admin/', admin.site.urls),
]

merchant/urls.py
from django.urls import path

from .views import MerchantIndexPageView, TableListPageView, TableCreatePageView
from .views import TableDetailPageView

app_name = 'merchant'
urlpatterns = [
    path('', MerchantIndexPageView.as_view(), name='index'),
    path('table', TableListPageView.as_view(), name='table-list'),
    path('table/new', TableCreatePageView.as_view(), name='table-create'),
    path('table/<key>', TableDetailPageView.as_view(), name='table-detail'),
]

merchant/models/merchant.py
from django.conf import settings
from django.db import models

from merchant.models import Table
from shared.models import Event

class Merchant(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    table_size = models.ForeignKey(Table, on_delete=models.SET_NULL, null=True)
    business_name = models.CharField(max_length=200)
    wares_description = models.TextField('Description of Wares')
    helper_legal_name = models.CharField(max_length=200, blank=True)
    helper_fan_name = models.CharField(max_length=200, blank=True)
    special_requests = models.TextField(blank=True)
    table_number = models.IntegerField(null=True, blank=True)
    table_assigned = models.BooleanField(default=False)

    def __str__(self):
        return "{} ({})".format(self.user.first_name, self.business_name)

merchant/models/table.py
from django.db import models

class Table(models.Model):
    key = models.CharField(max_length=4, primary_key=True, verbose_name="Internal Key")
    name = models.CharField(max_length=20, verbose_name="Table Name")
    order = models.IntegerField(default=0, verbose_name="Order to display")
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Table Cost")

    def __str__(self):
        return self.name

merchant/forms/merchant_form.py
from django import forms

from merchant.models import Merchant


class MerchantForm(forms.ModelForm):
    class Meta:
        model = Merchant
        fields = (
            'table_size',
            'business_name',
            'wares_description',
            'helper_legal_name',
            'helper_fan_name',
            'special_requests',
        )

merchant/forms/table_form.py
from django import forms

from merchant.models import Table

class TableForm(forms.ModelForm):
    class Meta:
        model = Table
        fields = (
            'key',
            'name',
            'order',
            'price'
        )

merchant/views/index.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView

class MerchantIndexPageView(TemplateView):
    template_name = 'merchant_index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

merchant/views/table_create.py
from django.views.generic.base import TemplateView
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator

from merchant.forms import TableForm

class TableCreatePageView(TemplateView):
    template_name = 'table_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['form'] = TableForm()

        return context
    
    def post(self, request, **kwargs):
        context = self.get_context_data(**kwargs)

        form = TableForm(request.POST)
        context['form'] = form

        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('merchant:table-list'))

        return self.render_to_response(context)

merchant/views/table_detail.py
from merchant.forms import TableForm
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView

from merchant.models import Table
from merchant.forms import TableForm

class TableDetailPageView(TemplateView):
    template_name = 'table_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        table = Table.objects.get(key=kwargs['key'])
        context['table'] = table
        context['form'] = TableForm(instance=table)

        return context
    
    def post(self, request, **kwargs):
        context = self.get_context_data(**kwargs)

        form = TableForm(request.POST, instance=context['table'])
        context['form'] = form

        if form.is_valid():
            form.save()
        
        return self.render_to_response(context)

merchant/views/table_list.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.base import TemplateView

from merchant.models import Table

class TableListPageView(TemplateView):
    template_name = 'table_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['tables'] = Table.objects.all()

        return context

merchant/templates/merchant_index.html
{% extends 'base.html' %}

{% block title %}PAWReg - Console{% endblock %}

{% block content %}
<div class="pt-5 row">
    <div class="col-2">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Admin</h5>
                <ul class="nav nav-pills flex-column">
                    <li class="nav-item">
                        <a href="{% url 'merchant:table-list' %}" class="nav-link">Tables</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="card mt-1">
            <div class="card-body">
                <h5 class="card-title">Merchants</h5>
                <ul class="nav nav-pills flex-column">
                    <li class="nav-item">
                        <a href="" class="nav-link">Merchants</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col">
        {% block merchant_section %}
        {% endblock %}
    </div>
</div>
{% endblock %}

merchant/templates/merchants_list.html
{% extends 'merchant_index.html' %}

{% block title %}PAWReg - Merchant Tables{% endblock %}

{% block merchant_section %}
<div class="row mt-2">
    <div class="col">
        <table class="table table-striped">
            <thead class="table-dark">
                <tr>
                    <td>Short Name</td>
                    <td>Long Name</td>
                    <td>Price</td>
                </tr>
            </thead>
            {% for table in tables %}
            <tr>
                <td>
                    <a href="{% url 'merchant:table-detail' table.key %}">{{table.key}}</a>
                </td>
                <td>{{table.name}}</td>
                <td>${{table.price}}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

merchant/templates/table_create.html
{% extends 'merchant_index.html' %}

{% block title %}PAWReg - Merchant Tables{% endblock %}

{% block merchant_section %}
<div class="row">
    <div class="col">
        <h1>Create Table</h1>
    </div>
</div>
<div class="row">
    <div class="col mb-3">
        <form action="{%url 'merchant:table-create' %}" method="post" class="form">
            {% csrf_token %}
            {{form.as_div}}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>
{% endblock %}

merchant/templates/table_detail.html
{% extends 'merchant_index.html' %}

{% block title %}PAWReg - Merchant Tables{% endblock %}

{% block merchant_section %}
<div class="row">
    <div class="col">
        <h1>Create Table</h1>
    </div>
</div>
<div class="row">
    <div class="col mb-3">
        <form action="{%url 'merchant:table-detail' table.key %}" method="post" class="form">
            {% csrf_token %}
            {{form.as_div}}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>
{% endblock %}

merchant/templates/table_list.html
{% extends 'merchant_index.html' %}

{% block title %}PAWReg - Merchant Tables{% endblock %}

{% block merchant_section %}
<div class="row">
    <div class="col">
        <h1>Tables</h1>
        <a href="{% url 'merchant:table-create' %}" class="btn btn-primary">Create Table</a>
    </div>
</div>
<div class="row mt-2">
    <div class="col">
        <table class="table table-striped">
            <thead class="table-dark">
                <tr>
                    <td>Short Name</td>
                    <td>Long Name</td>
                    <td>Price</td>
                </tr>
            </thead>
            {% for table in tables %}
            <tr>
                <td>
                    <a href="{% url 'merchant:table-detail' table.key %}">{{table.key}}</a>
                </td>
                <td>{{table.name}}</td>
                <td>${{table.price}}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}