PAWReg/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('client.urls')),
    path('console/', include('console.urls')),
    path('merchant/', include('merchant.urls')),
    path('admin/', admin.site.urls),
]

client/urls.py
from django.urls import path

from .views import HomePageView, DayPassPageView, ForgotPasswordPageView
from .views import SignupPageView, SigninPageView, SignoutPageView, ProfilePageView
from .views import RegisterPageView, SelectMembershipPageView, SelectProductsPageView
from .views import RegisterPaymentPageView, RegisterParentPageView, RegisterMerchantPageView
from .views import RegisterPartyPageView, RegisterVolunteerPageView

app_name = 'client'
urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path ('day_pass', DayPassPageView.as_view(), name='day-pass'),
    path('forgot', ForgotPasswordPageView.as_view(), name='forgot'),
    path('signup', SignupPageView.as_view(), name='signup'),
    path('signin', SigninPageView.as_view(), name='signin'),
    path('signout', SignoutPageView.as_view(), name='signout'),
    path('profile', ProfilePageView.as_view(), name='profile'),
    path('register', RegisterPageView.as_view(), name='register'),
    path('register/membership', SelectMembershipPageView.as_view(), name='register-membership'),
    path('register/products', SelectProductsPageView.as_view(), name='register-products'),
    path('register/parent', RegisterParentPageView.as_view(), name='register-parent'),
    path('register/merchant', RegisterMerchantPageView.as_view(), name='register-merchant'),
    path('register/party', RegisterPartyPageView.as_view(), name='register-party'),
    path('register/volunteer', RegisterVolunteerPageView.as_view(), name='register-volunteer'),
    path('register/payment', RegisterPaymentPageView.as_view(), name='register-payment'),
]

console/urls.py
from django.urls import path

from .views import ConsoleIndexPageView, EventsListPageView, EventsCreatePageView, EventsDetailsPageView, MembershipsCreatePageView, MembershipsDetailPageView, ProductCreatePageView, ProductDetailPageView

app_name = 'console'
urlpatterns = [
    path('', ConsoleIndexPageView.as_view(), name='index'),
    path('events', EventsListPageView.as_view(), name='events-list'),
    path('events/new', EventsCreatePageView.as_view(), name='events-create'),
    path('events/<int:event_id>', EventsDetailsPageView.as_view(), name='events-detail'),
    path('events/<int:event_id>/memberships', MembershipsCreatePageView.as_view(), name='memberships-create'),
    path('events/<int:event_id>/memberships/<int:membership_id>', MembershipsDetailPageView.as_view(), name='memberships-detail'),
    path('events/<int:event_id>/products', ProductCreatePageView.as_view(), name='products-create'),
    path('events/<int:event_id>/products/<int:product_id>', ProductDetailPageView.as_view(), name='products-detail'),
]

merchant/urls.py
from django.urls import path

from .views import MerchantIndexPageView, TableListPageView, TableCreatePageView
from .views import TableDetailPageView

app_name = 'merchant'
urlpatterns = [
    path('', MerchantIndexPageView.as_view(), name='index'),
    path('table', TableListPageView.as_view(), name='table-list'),
    path('table/new', TableCreatePageView.as_view(), name='table-create'),
    path('table/<key>', TableDetailPageView.as_view(), name='table-detail'),
]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>
  <body>
    <nav class="p-3 navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a href="{% url 'client:index' %}" class="navbar-brand">PAWReg</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="navbar-item">
                        <a href="{% url 'client:profile' %}" class="nav-link">Profile</a>
                    </li>
                    <li class="navbar-item">
                        <a href="{% url 'console:index' %}" class="nav-link">Console</a>
                    </li>
                    <li class="navbar-item">
                        <a href="{% url 'merchant:index' %}" class="nav-link">Merchants</a>
                    </li>
                </ul>
            </div>
            {% if user.is_authenticated %}
            <div class="text-end">
                <a href="{% url 'client:signout' %}" class="btn btn-outline-light">Logout</a>
            </div>
            {% endif %}
        </div>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>